[customizations.installer.kickstart]
contents = """
# Use graphical installer
graphical

# Language & keyboard
lang en_US.UTF-8
keyboard us

# Networking
network --bootproto=dhcp --device=link --activate --onboot=on

# Timezone
timezone America/New_York --utc

# Let Anaconda ask for installation disk
# (INTENTIONALLY no storage directives)

# Root password
rootpw --iscrypted $6$xZKnpH2gttrEiQXd$PczHGV1o5UcVmidCOBuJrGJdncAq9deFZoLZt8aV1lBC1CXttecg1z6uAkGdd8QUaLtuNajSZwWs.2CFJmgeJ/ 

# User
user --name=zpeppler \
     --groups=wheel,video,input \
     --shell=/bin/bash \
     --password=$6$xZKnpH2gttrEiQXd$PczHGV1o5UcVmidCOBuJrGJdncAq9deFZoLZt8aV1lBC1CXttecg1z6uAkGdd8QUaLtuNajSZwWs.2CFJmgeJ/ \
     --iscrypted

# Security
firewall --enabled
selinux --enforcing

# Services
services --enabled=sshd


# Reboot after install
reboot

"""
