name: build container -> niri-bootc
run-name: building container -> niri-bootc
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  niri-bootc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: run podman build
        run: podman build -t niri-bootc --disable-compression=false .

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_PAT }}" | podman login ghcr.io -u "${{ github.repository_owner }}" --password-stdin

      - name: push image to ghcr.io
        run: |
          podman tag niri-bootc ghcr.io/${{ github.repository_owner }}/niri-bootc:latest
          podman push ghcr.io/${{ github.repository_owner }}/niri-bootc:latest
