name: build container -> niri-bootc
run-name: building container -> niri-bootc
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  niri-bootc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run podman build
        run: podman build -t niri-bootc --disable-compression=false .
      - name: push image to ghcr.io
        run: |
          podman tag niri-bootc ghcr.io/zpeppler/niri-bootc:latest
          podman push ghcr.io/zpeppler/niri-bootc:latest --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
